### PR TITLE
Revert "Make !uptime behave if the stream isn't live"

### PR DESCRIPTION
**Pull request by BatedUrGonnaDie**
Reverts BatedUrGonnaDie/salty_bot#15

### CODE REVIEW

**Comment by glacials** [comment]
lol

**Comment by BatedUrGonnaDie** [comment]
You broke the is_live function for !race when you changed it .-.

**Comment by glacials** [comment]
hm ok, can you explain where it broke? i'm still new to python so i can't trace the code very well. i don't see is_live being called anywhere

**Comment by BatedUrGonnaDie** [comment]
I'm dumb and forgot that I changed my code in the past.  Sorry about that.  You didn't break anything.

**Pull request merged**
